### ISSUE TITLE
Add support to rollup to multiselect picklists

### ISSUE THREAD

**Issue by ssk42** [jamessimone/apex-rollup#53]
Currently, Rollup will just produce one string of comma-delineated values as multiselect picklist value. 

Repro steps:
1. Create a record triggered flow (after create) for child object
2. Add a Get Element for Parent object
3. Add a Get Element for the correct children of the Parent
4. Rollup Invocable with the following variables: 
- Calcitemrollupfield of a String
- Lookup Field on Calc Item is a Lookup to Parent
- Lookup field on Rollup Object is Id of Parent
- Rollup Context is update
- Rollup object field is a multiselect picklist field
- Rollup op is CONCAT_DISTINCT
- Rollup target's SObject name is Opportunity
- Records to rollup is variable from Step 3

Envrionment Variables:
Spring 21/api 51

**Comment by jamessimone** [comment]
@ssk42 first of all - it's an honor hosting an issue for you here. I can commit to getting this fixed in the near future; if not tonight, by end of tomorrow certainly.

**Comment by jamessimone** [comment]
@ssk42 - you should be all set with the [latest release](/releases/tag/v1.1.9) - enjoy!

**Comment by ssk42** [comment]
This gets closer but doesn't quite fix it. The first two items/strings/whathaveyou for some reason aren't comma delineated and so they still come across together as one item. After that though every other item rolls up great into a multiselect picklist. Thanks for getting work into this so quick!

**Comment by jamessimone** [comment]
@ssk42 iiiiiinteresting. Can you share a screenshot (or even just text) of what the text values for the first few items are? It should be simply adding “;” between values, so I want to ensure I understand the input so I can reproduce the output.

**Comment by ssk42** [comment]
Same repro steps as above.  It's mostly just that the rollupField__c value is now testAccount1testAccount2;testAccount3, etc.

**Comment by jamessimone** [comment]
Officially closed with @ssk42 's blessing as part of #55
